### ISSUE TITLE
__module__ instead of @__MODULE__

### ISSUE THREAD

**Issue by thautwarm** [tkf/Awaits.jl#1]
https://github.com/tkf/Awaits.jl/blob/24712770164cbd22c4de2568dc4ace1c75553eca/src/Awaits.jl#L201

As you insert the expression, `$(@__MODULE__)` shall be evaluated to `$(Awaits)`, I think it mustn't be your purpose. So use `__module__` to access the module where `@go` gets invoked.

**Comment by tkf** [comment]
`@__MODULE__` is actually what I need there.  I want to use `Awaits.@await` even if it is not imported in `__module__` namespace.

Did you get an unexpected behavior due to this?

**Comment by thautwarm** [comment]
No.  If this is your purpose, I think it okay to write `Awaits` explicitly, but it'll then be not an issue.

**Comment by tkf** [comment]
Yea, that's an option.  But `$(@__MODULE__).@await` keeps working if I move it to a different (sub)module, for example.
